### ISSUE TITLE
Anomalies in the report of the metrics

### ISSUE THREAD

**Issue by mazzy89** [spreaker/prometheus-pgbouncer-exporter#12]
I was running *pgbouncer* as pods in my k8s cluster. 3 replicas. The metrics reported were very strange.

![image](https://user-images.githubusercontent.com/5463218/56849795-8c35eb00-68f9-11e9-885c-54ffcdcfff02.png)

for instance the graph above reports the total query time before and after the scaling. The values are a bit weird when the replicas are 3. It reports as avg 16/17s which is a huge number and definitely not encountered in reality. When scaled to 1 then all values start to make a lot of sense.

Maybe it is not an issue of the exporter. But I'm not sure where to start to dig. Any thoughts?

**Comment by mazzy89** [comment]
I just read the YAML and one option says:

```yaml
# Extra labels to add to all metrics exported for this pgbouncer
# instance. Required if you have configured multiple pgbouncers,
# in order to export an unique set of metrics.
extra_labels:
  pool_id: 1
```

should I maybe configure this when pgbouncer replicas are > 1?
