### ISSUE TITLE
How to config prometheus.yml ?

### ISSUE THREAD

**Issue by zuoRambo** [spreaker/prometheus-pgbouncer-exporter#16]
```yml
apiVersion: v1
data:
  alerts: |
    {}
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    rule_files:
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: pgbouncer
      relabel_configs:
      - source_labels: [ 10.6.87.237:9100, 10.6.87.238:9100]
        target_label: hostname
```

**Comment by zuoRambo** [comment]
```yml
    - job_name: pgbouncer
      relabel_configs:
      - source_labels: [ 10.6.87.237:9100, 10.6.87.238:9100]
        target_label: hostname
```
This section was added. Right?
