### ISSUE TITLE
Forcing to use password

### ISSUE THREAD

**Issue by aekiratli** [spreaker/prometheus-pgbouncer-exporter#32]
config:

```
exporter_host: 0.0.0.0
exporter_port: 9643
pgbouncers:
  - dsn: postgresql://localhost:6432/pgbouncer
    connect_timeout: 5
    include_databases:
    exclude_databases:
      - pgbouncer
```

error:

```
{"asctime": "2020-11-16 20:36:19", "levelname": "INFO", "message": "Exporter is starting up"}
{"asctime": "2020-11-16 20:36:19", "levelname": "INFO", "message": "Config file successfully read from /etc/pgbouncer-exporter.yaml"}
{"asctime": "2020-11-16 20:36:19", "levelname": "ERROR", "message": "Unable fetch metrics from postgresql:***@localhost:6432/pgbouncer", "exception": "fe_sendauth: no password supplied\n"}
{"asctime": "2020-11-16 20:36:19", "levelname": "INFO", "message": "Exporter listening on 0.0.0.0:9643"}

```

Eventhough dsn does not include password, it asks me for a password, it should bypass password when dsn does not include password
